from dx_modelzoo.models.depth_estimation.fast_depth import FastDepth
from dx_modelzoo.models.depth_estimation.scdepth import SCDepthV3
from dx_modelzoo.models.face_attribute.face_attr_resnet import FaceAttrResnetV1_18
from dx_modelzoo.models.face_detection.retinaface import RetinaFace_MobileNet025, RetinaFace_MobileNetV1
from dx_modelzoo.models.face_detection.scrfd import SCRFD2_5G, SCRFD10G, SCRFD500M
from dx_modelzoo.models.face_detection.ulfgfd import (
    ULFGFD_RFB_320,
    ULFGFD_RFB_320_WO_PP,
    ULFGFD_RFB_640,
    ULFGFD_Slim_320,
    ULFGFD_Slim_320_WO_PP,
)
from dx_modelzoo.models.face_detection.yolo import (
    YOLOv5m_Face,
    YOLOv5N_Face,
    YOLOv5s_Face,
    YOLOv7_Face,
    YOLOv7_W6_Face,
    YOLOv7_W6_TTA_Face,
    YOLOv7s_Face,
)
from dx_modelzoo.models.face_landmark.tddfa_v2 import TDDFA_V2_MobileNet05, TDDFA_V2_MobileNetV1, TDDFA_V2_ResNet22
from dx_modelzoo.models.face_recognition.arcface import (
    ArcFace_IResNet50_MS1M,
    ArcFace_IResNet100_MS1M,
    ArcFace_MobileFaceNet,
    ArcFace_R50,
)
from dx_modelzoo.models.hand_landmark.mediapipe_hands import MediaPipeHandsLite
from dx_modelzoo.models.image_classification.alexnet import AlexNet
from dx_modelzoo.models.image_classification.casvit import CasViT_M, CasViT_S, CasViT_T, CasViT_XS
from dx_modelzoo.models.image_classification.convnext import (
    ConvNeXtBase224_1k,
    ConvNeXtBase224_22k_1k,
    ConvNeXtBase384_22k_1k,
    ConvNeXtLarge224_1k,
    ConvNeXtSmall224_1k,
    ConvNeXtTiny224_1k,
)
from dx_modelzoo.models.image_classification.densenet import DenseNet121, DenseNet161, DenseNet169, DenseNet201
from dx_modelzoo.models.image_classification.efficientformer import (
    EfficientFormer_L1,
    EfficientFormer_L3,
    EfficientFormer_L7,
    EfficientFormerV2_L,
    EfficientFormerV2_S0,
    EfficientFormerV2_S1,
    EfficientFormerV2_S2,
)
from dx_modelzoo.models.image_classification.efficientnet import (
    EfficientNetB0,
    EfficientNetB1,
    EfficientNetB2,
    EfficientNetB3,
    EfficientNetB4,
    EfficientNetB5,
    EfficientNetB6,
    EfficientNetB7,
    EfficientNetEdgeTPULarge,
    EfficientNetEdgeTPUMedium,
    EfficientNetEdgeTPUSmall,
    EfficientNetLite0,
    EfficientNetLite1,
    EfficientNetLite2,
    EfficientNetLite3,
    EfficientNetLite4,
    EfficientNetV2L,
    EfficientNetV2M,
    EfficientNetV2S,
)
from dx_modelzoo.models.image_classification.fastvit import (
    FastViT_MA36,
    FastViT_S12,
    FastViT_SA12,
    FastViT_SA24,
    FastViT_SA36,
    FastViT_T8,
    FastViT_T12,
)
from dx_modelzoo.models.image_classification.ghostnet import GhostNet
from dx_modelzoo.models.image_classification.googlenet import GoogLeNet
from dx_modelzoo.models.image_classification.hardnet import HarDNet39DS, HarDNet68
from dx_modelzoo.models.image_classification.inception import InceptionV1, InceptionV3
from dx_modelzoo.models.image_classification.levit import LeViT128, LeViT128S, LeViT192, LeViT256, LeViT384
from dx_modelzoo.models.image_classification.mambaout import MambaOutBase, MambaOutFemto, MambaOutSmall, MambaOutTiny
from dx_modelzoo.models.image_classification.maxvit import MaxViT_Tiny
from dx_modelzoo.models.image_classification.mnasnet import MnasNet0_5, MnasNet0_75, MnasNet1_0, MnasNet1_3
from dx_modelzoo.models.image_classification.mobilenet import (
    MobileNetV1,
    MobileNetV2,
    MobileNetV3Large,
    MobileNetV3Small,
)
from dx_modelzoo.models.image_classification.mobilevit import MobileViT_Small, MobileViT_X_Small, MobileViT_XX_Small
from dx_modelzoo.models.image_classification.osnet import OSNet0_5, OSNet0_25
from dx_modelzoo.models.image_classification.poolformer import (
    PoolFormerM36,
    PoolFormerM48,
    PoolFormerS12,
    PoolFormerS24,
    PoolFormerS36,
)
from dx_modelzoo.models.image_classification.regnet import (
    RegNetX400MF,
    RegNetX800MF,
    RegNetX_1_6GF,
    RegNetX_1_6GF_3,
    RegNetX_3_2GF,
    RegNetX_8GF,
    RegNetX_16GF,
    RegNetX_32GF,
    RegNetY200MF,
    RegNetY400MF,
    RegNetY800MF,
    RegNetY_1_6GF,
    RegNetY_3_2GF,
    RegNetY_8GF,
    RegNetY_16GF,
    RegNetY_32GF,
)
from dx_modelzoo.models.image_classification.repghost import RepGhost_1_0x, RepGhost_2_0x
from dx_modelzoo.models.image_classification.repvgg import RepVGGA0, RepVGGA1, RepVGGA2, RepVGGB0, RepVGGB1
from dx_modelzoo.models.image_classification.resmlp import ResMLP12, ResMLP24, ResMLP36
from dx_modelzoo.models.image_classification.resnet import (
    ResNet18,
    ResNet18_BRECQ,
    ResNet34,
    ResNet50,
    ResNet101,
    ResNet152,
)
from dx_modelzoo.models.image_classification.resnext import (
    ResNeXt26_32x4d,
    ResNeXt50_32x4d,
    ResNeXt50_32x4d_imgclsmob,
    ResNeXt101_32x8d,
    ResNeXt101_64x4d,
)
from dx_modelzoo.models.image_classification.shufflenet import (
    ShuffleNetV1_x1_0,
    ShuffleNetV2_x0_5,
    ShuffleNetV2_x1_0,
    ShuffleNetV2_x1_5,
    ShuffleNetV2_x2_0,
)
from dx_modelzoo.models.image_classification.squeezenet import SqueezeNet1_0, SqueezeNet1_1, SqueezeNet1_3
from dx_modelzoo.models.image_classification.vgg import VGG11, VGG11BN, VGG13, VGG13BN, VGG16, VGG16BN, VGG19, VGG19BN
from dx_modelzoo.models.image_classification.vit import (
    BeitBasePatch16_224,
    BeitBasePatch16_384,
    BeitLargePatch16_224,
    BeitLargePatch16_384,
    DeiTBase_224,
    DeiTBase_384,
    DeiTBaseDistilled_224,
    DeiTBaseDistilled_384,
    DeiTSmall_224,
    DeiTSmallDistilled_224,
    DeiTTiny_224,
    DeiTTinyDistilled_224,
    ViT_Base_BN,
    ViT_Base_P16,
    ViT_Base_P16_224,
    ViT_Base_P16_384,
    ViT_Base_P32,
    ViT_Base_P32_384,
    ViT_Large_P32,
    ViT_Small_P16_224,
    ViT_Tiny_P16_224,
)
from dx_modelzoo.models.image_classification.wideresnet import WideResNet50_2, WideResNet101_2
from dx_modelzoo.models.image_classification.yolo import YOLO26l_cls, YOLO26m_cls, YOLO26n_cls, YOLO26s_cls, YOLO26x_cls
from dx_modelzoo.models.image_denoising.dncnn import (
    DnCNN_15,
    DnCNN_25,
    DnCNN_50,
    DnCNN_Color,
    DnCNN_Gray,
    DnCNN_Gray_V2,
)
from dx_modelzoo.models.image_segmentation.bisenet import BiSeNetV1, BiSeNetV2
from dx_modelzoo.models.image_segmentation.deeplab import (
    DeepLabV3MobilenetV2,
    DeepLabV3PlusDRN,
    DeepLabV3PlusMobilenet,
    DeepLabV3PlusMobileNetV2,
    DeepLabV3PlusResnet,
    DeepLabV3PlusResNet50,
    DeepLabV3PlusResNet101,
)
from dx_modelzoo.models.image_segmentation.fastsam import FastSAM_S
from dx_modelzoo.models.image_segmentation.fcn import FCN8_ResNet18, FCN8_ResNet50
from dx_modelzoo.models.image_segmentation.segformer import SegFormer_b0_512x1024, SegFormer_b0_512x1024_H
from dx_modelzoo.models.image_segmentation.unet import UNet_MobileNetV2
from dx_modelzoo.models.image_segmentation.yolact import YOLACT_RegNetX_1_6gf, YOLACT_RegNetX_800mf
from dx_modelzoo.models.image_segmentation.yolo import (
    Yolo26L_Seg,
    Yolo26M_Seg,
    Yolo26N_Seg,
    Yolo26S_Seg,
    Yolo26X_Seg,
    YoloV5L_Seg,
    YoloV5M_Seg,
    YoloV5N_Seg,
    YoloV5S_Seg,
    YoloV8M_Seg,
    YoloV8N_Seg,
    YoloV8S_Seg,
)
from dx_modelzoo.models.low_light_enhancement.zero_dce import ZeroDCE
from dx_modelzoo.models.object_detection.centernet import CenterNet_ResNet18, CenterNet_ResNet50
from dx_modelzoo.models.object_detection.damoyolo import (
    DamoYoloL,
    DamoYoloM,
    DamoYoloS,
    DamoYoloT,
    damoyolo_tinynas_l20_m,
    damoyolo_tinynas_l20_t,
    damoyolo_tinynas_l25_s,
)
from dx_modelzoo.models.object_detection.efficientdet import (
    EfficientDet_D0,
    EfficientDet_D1,
    EfficientDet_D2,
    EfficientDet_D3,
    EfficientDet_D4,
    EfficientDet_D5,
    EfficientDet_D6,
)
from dx_modelzoo.models.object_detection.nanodet import (
    NanoDet,
    NanoDet_Plus,
    NanoDet_Plus_15,
    NanoDet_RepVGGA,
    NanoDet_RepVGGA12,
)
from dx_modelzoo.models.object_detection.ssd import SSDMV1, SSDVGG16, SSDMV2Lite
from dx_modelzoo.models.object_detection.yolo import (
    YOLOV3_416_PPU,
    YOLOV3_608_PPU,
    YOLOV4_PPU,
    YOLOV5S_PPU,
    YOLOV7_PPU,
    YOLOV7X_PPU,
    YOLOV8N_PPU,
    YOLOV8S_PPU,
    YOLOV9T_PPU,
    YOLOV11N_PPU,
    YOLOV12N_PPU,
    YOLOXS_PPU,
    YOLO26l,
    YOLO26m,
    YOLO26n,
    YOLO26s,
    YOLO26x,
    YOLO_DeepX_640,
    YoloV3,
    YoloV3_416,
    YoloV3_Gluon_416,
    YoloV3_Gluon_608,
    YoloV3_Tiny,
    YOLOV3Tiny_PPU,
    YoloV4_640,
    YoloV4_Leaky_512,
    YoloV4Tiny_416,
    YoloV5L,
    YoloV5L6_1280,
    YoloV5L_640,
    YoloV5M,
    YoloV5M6_1,
    YoloV5M6_61_1280,
    YoloV5M6_1280,
    YoloV5M_640,
    YoloV5M_WoSpp_640,
    YoloV5N,
    YoloV5N6_61_1280,
    YoloV5N6_1280,
    YoloV5S,
    YoloV5S6_61_1280,
    YoloV5S6_1280,
    YoloV5S_320,
    YoloV5S_640,
    YoloV5S_BboxDecoding_640,
    YoloV5S_C3tr_640,
    YoloV5S_WoSpp_640,
    YoloV5X6_1280,
    YoloV5X_640,
    YoloV5XS_WoSpp_512,
    YoloV6L_640,
    YoloV6M_640,
    YoloV6N,
    YoloV6N0_1_0,
    YoloV6N0_2_1,
    YoloV6N6_1280,
    YoloV6N_NmsCore_640,
    YoloV6S6_1280,
    YoloV6S_640,
    YoloV7,
    YoloV7_W6,
    YoloV7_W6_wo_decoding,
    YoloV7_wo_decoding,
    YoloV7_X,
    YoloV7D6_1280,
    YoloV7E6,
    YoloV7E6E_1280,
    YoloV7Tiny,
    YoloV8L,
    YoloV8M,
    YoloV8N,
    YoloV8S,
    YoloV8S_decoding,
    YoloV8X,
    YoloV9_GELAN_C,
    YoloV9C,
    YoloV9M,
    YoloV9S,
    YoloV9T,
    YoloV10B,
    YoloV10L,
    YoloV10M,
    YoloV10N,
    YoloV10N_PPU,
    YoloV10S,
    YoloV10X,
    YoloV11L,
    YoloV11M,
    YoloV11N,
    YoloV11S,
    YoloV11X,
    YoloXL_640,
    YoloXLLeaky,
    YoloXM_640,
    YoloXN_416,
    YoloXS,
    YoloXSLeaky,
    YoloXSWideLeaky,
    YoloXTiny,
    YoloXTiny_416,
    YoloXX_640,
)
from dx_modelzoo.models.open_clip.convnext import (
    ConvNextBase_w_320_laion_aesthetic_s13b_b82k,
    ConvNextBase_w_laion2b_s13b_b82k_augreg,
    ConvNextLarge_d_laion2b_s26b_b102k_augreg,
    ConvNextLarge_w_320_laion2b_s29b_b131k_ft_soup,
)
from dx_modelzoo.models.open_clip.resnet import RN50x16_openai, RN50x64_openai
from dx_modelzoo.models.open_clip.ViT import (
    ViT_B_16_dfn2b,
    ViT_B_16_quickgelu_metaclip_fullcc,
    ViT_B_32_256_datacomp_s34b_b68k,
    ViT_L_14_336_openai,
    ViT_L_14_CLIPA_336_datacomp1b,
    ViT_L_14_CLIPA_datacomp1b,
    ViT_L_14_datacomp_xl_s13b_b90k,
    ViT_L_14_quickgelu_dfn2b,
)
from dx_modelzoo.models.oriented_object_detection.yolo26 import (
    YOLO26l_OBB,
    YOLO26m_OBB,
    YOLO26n_OBB,
    YOLO26s_OBB,
    YOLO26x_OBB,
)
from dx_modelzoo.models.person_attribute.deepmar import DeepMAR_ResNet18, DeepMAR_ResNet50
from dx_modelzoo.models.person_reid.osnet import OSNetX1_0_ReID
from dx_modelzoo.models.person_reid.repvgg import RepVGGA0_ReID
from dx_modelzoo.models.pose_estimation.centerpose import (
    CenterPose_RegNetX_1_6GF_FPN,
    CenterPose_RegNetX_800MF,
    CenterPose_RepVGG_A0,
)
from dx_modelzoo.models.pose_estimation.yolo import (
    Yolo26L_Pose,
    Yolo26M_Pose,
    Yolo26N_Pose,
    Yolo26S_Pose,
    Yolo26X_Pose,
    YOLOV8L_Pose,
    YOLOV8M_Pose,
    YOLOV8N_Pose,
    YOLOV8S_Pose,
    YOLOV8X_Pose,
)
from dx_modelzoo.models.super_resolution.espcn import ESPCN_x2, ESPCN_x3, ESPCN_x4

MODEL_DICT = {
    YOLACT_RegNetX_1_6gf.__name__: YOLACT_RegNetX_1_6gf,
    YOLACT_RegNetX_800mf.__name__: YOLACT_RegNetX_800mf,
    YOLO26l_OBB.__name__: YOLO26l_OBB,
    YOLO26m_OBB.__name__: YOLO26m_OBB,
    YOLO26n_OBB.__name__: YOLO26n_OBB,
    YOLO26s_OBB.__name__: YOLO26s_OBB,
    YOLO26x_OBB.__name__: YOLO26x_OBB,
    FCN8_ResNet18.__name__: FCN8_ResNet18,
    FCN8_ResNet50.__name__: FCN8_ResNet50,
    YOLO26n_cls.__name__: YOLO26n_cls,
    YOLO26s_cls.__name__: YOLO26s_cls,
    YOLO26m_cls.__name__: YOLO26m_cls,
    YOLO26l_cls.__name__: YOLO26l_cls,
    YOLO26x_cls.__name__: YOLO26x_cls,
    RepGhost_1_0x.__name__: RepGhost_1_0x,
    RepGhost_2_0x.__name__: RepGhost_2_0x,
    ViT_Large_P32.__name__: ViT_Large_P32,
    ViT_Base_P16.__name__: ViT_Base_P16,
    ViT_Base_P32.__name__: ViT_Base_P32,
    ViT_Base_BN.__name__: ViT_Base_BN,
    ViT_Base_P16_224.__name__: ViT_Base_P16_224,
    ViT_Base_P16_384.__name__: ViT_Base_P16_384,
    ViT_Base_P32_384.__name__: ViT_Base_P32_384,
    ViT_Small_P16_224.__name__: ViT_Small_P16_224,
    ViT_Tiny_P16_224.__name__: ViT_Tiny_P16_224,
    MobileViT_Small.__name__: MobileViT_Small,
    MobileViT_X_Small.__name__: MobileViT_X_Small,
    MobileViT_XX_Small.__name__: MobileViT_XX_Small,
    MaxViT_Tiny.__name__: MaxViT_Tiny,
    FastViT_MA36.__name__: FastViT_MA36,
    FastViT_S12.__name__: FastViT_S12,
    FastViT_SA12.__name__: FastViT_SA12,
    FastViT_SA24.__name__: FastViT_SA24,
    FastViT_SA36.__name__: FastViT_SA36,
    FastViT_T12.__name__: FastViT_T12,
    FastViT_T8.__name__: FastViT_T8,
    PoolFormerM36.__name__: PoolFormerM36,
    PoolFormerM48.__name__: PoolFormerM48,
    PoolFormerS12.__name__: PoolFormerS12,
    PoolFormerS24.__name__: PoolFormerS24,
    PoolFormerS36.__name__: PoolFormerS36,
    MambaOutBase.__name__: MambaOutBase,
    MambaOutFemto.__name__: MambaOutFemto,
    MambaOutSmall.__name__: MambaOutSmall,
    MambaOutTiny.__name__: MambaOutTiny,
    ConvNeXtLarge224_1k.__name__: ConvNeXtLarge224_1k,
    ConvNeXtSmall224_1k.__name__: ConvNeXtSmall224_1k,
    ConvNeXtTiny224_1k.__name__: ConvNeXtTiny224_1k,
    ConvNeXtBase224_22k_1k.__name__: ConvNeXtBase224_22k_1k,
    ConvNeXtBase384_22k_1k.__name__: ConvNeXtBase384_22k_1k,
    ConvNeXtBase224_1k.__name__: ConvNeXtBase224_1k,
    CasViT_XS.__name__: CasViT_XS,
    CasViT_T.__name__: CasViT_T,
    CasViT_S.__name__: CasViT_S,
    CasViT_M.__name__: CasViT_M,
    LeViT128.__name__: LeViT128,
    LeViT128S.__name__: LeViT128S,
    LeViT192.__name__: LeViT192,
    LeViT256.__name__: LeViT256,
    LeViT384.__name__: LeViT384,
    ResMLP12.__name__: ResMLP12,
    ResMLP24.__name__: ResMLP24,
    ResMLP36.__name__: ResMLP36,
    ResNet18.__name__: ResNet18,
    ResNet18_BRECQ.__name__: ResNet18_BRECQ,
    YoloV5N.__name__: YoloV5N,
    DeepLabV3PlusMobilenet.__name__: DeepLabV3PlusMobilenet,
    ResNet34.__name__: ResNet34,
    ResNet50.__name__: ResNet50,
    ResNet101.__name__: ResNet101,
    ResNet152.__name__: ResNet152,
    YoloV5S.__name__: YoloV5S,
    YoloV5S_320.__name__: YoloV5S_320,
    YoloV6N.__name__: YoloV6N,
    YoloV6N0_1_0.__name__: YoloV6N0_1_0,
    YoloV6N0_2_1.__name__: YoloV6N0_2_1,
    YoloV5M.__name__: YoloV5M,
    YoloV5L.__name__: YoloV5L,
    YoloV6N.__name__: YoloV6N,
    DeepLabV3PlusDRN.__name__: DeepLabV3PlusDRN,
    DeepLabV3PlusMobileNetV2.__name__: DeepLabV3PlusMobileNetV2,
    DeepLabV3PlusResNet101.__name__: DeepLabV3PlusResNet101,
    DeepLabV3PlusResNet50.__name__: DeepLabV3PlusResNet50,
    DeepLabV3PlusResnet.__name__: DeepLabV3PlusResnet,
    ResNeXt50_32x4d.__name__: ResNeXt50_32x4d,
    ResNeXt50_32x4d_imgclsmob.__name__: ResNeXt50_32x4d_imgclsmob,
    ResNeXt26_32x4d.__name__: ResNeXt26_32x4d,
    ResNeXt101_32x8d.__name__: ResNeXt101_32x8d,
    ResNeXt101_64x4d.__name__: ResNeXt101_64x4d,
    RegNetX400MF.__name__: RegNetX400MF,
    RegNetX800MF.__name__: RegNetX800MF,
    RegNetY200MF.__name__: RegNetY200MF,
    RegNetY400MF.__name__: RegNetY400MF,
    RegNetY800MF.__name__: RegNetY800MF,
    ShuffleNetV1_x1_0.__name__: ShuffleNetV1_x1_0,
    ShuffleNetV2_x0_5.__name__: ShuffleNetV2_x0_5,
    ShuffleNetV2_x1_0.__name__: ShuffleNetV2_x1_0,
    ShuffleNetV2_x1_5.__name__: ShuffleNetV2_x1_5,
    ShuffleNetV2_x2_0.__name__: ShuffleNetV2_x2_0,
    DenseNet121.__name__: DenseNet121,
    DenseNet161.__name__: DenseNet161,
    DenseNet169.__name__: DenseNet169,
    DenseNet201.__name__: DenseNet201,
    EfficientNetEdgeTPUSmall.__name__: EfficientNetEdgeTPUSmall,
    EfficientNetEdgeTPUMedium.__name__: EfficientNetEdgeTPUMedium,
    EfficientNetEdgeTPULarge.__name__: EfficientNetEdgeTPULarge,
    EfficientNetB0.__name__: EfficientNetB0,
    EfficientNetB1.__name__: EfficientNetB1,
    EfficientNetB2.__name__: EfficientNetB2,
    EfficientNetB3.__name__: EfficientNetB3,
    EfficientNetB4.__name__: EfficientNetB4,
    EfficientNetB5.__name__: EfficientNetB5,
    EfficientNetB6.__name__: EfficientNetB6,
    EfficientNetB7.__name__: EfficientNetB7,
    EfficientNetV2S.__name__: EfficientNetV2S,
    EfficientNetV2M.__name__: EfficientNetV2M,
    EfficientNetV2L.__name__: EfficientNetV2L,
    EfficientNetLite0.__name__: EfficientNetLite0,
    EfficientNetLite1.__name__: EfficientNetLite1,
    EfficientNetLite2.__name__: EfficientNetLite2,
    EfficientNetLite3.__name__: EfficientNetLite3,
    EfficientNetLite4.__name__: EfficientNetLite4,
    EfficientFormer_L1.__name__: EfficientFormer_L1,
    EfficientFormer_L3.__name__: EfficientFormer_L3,
    EfficientFormer_L7.__name__: EfficientFormer_L7,
    EfficientFormerV2_L.__name__: EfficientFormerV2_L,
    EfficientFormerV2_S0.__name__: EfficientFormerV2_S0,
    EfficientFormerV2_S1.__name__: EfficientFormerV2_S1,
    EfficientFormerV2_S2.__name__: EfficientFormerV2_S2,
    GhostNet.__name__: GhostNet,
    GoogLeNet.__name__: GoogLeNet,
    HarDNet39DS.__name__: HarDNet39DS,
    MobileNetV1.__name__: MobileNetV1,
    MobileNetV2.__name__: MobileNetV2,
    SqueezeNet1_0.__name__: SqueezeNet1_0,
    SqueezeNet1_1.__name__: SqueezeNet1_1,
    SqueezeNet1_3.__name__: SqueezeNet1_3,
    VGG11BN.__name__: VGG11BN,
    VGG19BN.__name__: VGG19BN,
    WideResNet101_2.__name__: WideResNet101_2,
    WideResNet50_2.__name__: WideResNet50_2,
    AlexNet.__name__: AlexNet,
    VGG11.__name__: VGG11,
    VGG13.__name__: VGG13,
    VGG13BN.__name__: VGG13BN,
    VGG16.__name__: VGG16,
    VGG16BN.__name__: VGG16BN,
    VGG19.__name__: VGG19,
    MobileNetV3Large.__name__: MobileNetV3Large,
    MobileNetV3Small.__name__: MobileNetV3Small,
    OSNet0_25.__name__: OSNet0_25,
    OSNet0_5.__name__: OSNet0_5,
    RepVGGA1.__name__: RepVGGA1,
    RepVGGA2.__name__: RepVGGA2,
    RepVGGA0.__name__: RepVGGA0,
    RepVGGB0.__name__: RepVGGB0,
    RepVGGB1.__name__: RepVGGB1,
    YoloXS.__name__: YoloXS,
    YoloV3.__name__: YoloV3,
    YoloV3_416.__name__: YoloV3_416,
    YoloV3_Tiny.__name__: YoloV3_Tiny,
    YoloV7.__name__: YoloV7,
    YoloV7_wo_decoding.__name__: YoloV7_wo_decoding,
    YoloV7E6.__name__: YoloV7E6,
    YoloV7Tiny.__name__: YoloV7Tiny,
    YoloV7_X.__name__: YoloV7_X,
    YoloV7_W6.__name__: YoloV7_W6,
    YoloV7_W6_wo_decoding.__name__: YoloV7_W6_wo_decoding,
    YoloV8L.__name__: YoloV8L,
    YoloV8S_decoding.__name__: YoloV8S_decoding,
    YoloV9C.__name__: YoloV9C,
    YoloV9S.__name__: YoloV9S,
    YoloV9T.__name__: YoloV9T,
    YoloV9_GELAN_C.__name__: YoloV9_GELAN_C,
    YoloV9M.__name__: YoloV9M,
    SSDMV1.__name__: SSDMV1,
    SSDMV2Lite.__name__: SSDMV2Lite,
    DnCNN_15.__name__: DnCNN_15,
    DnCNN_25.__name__: DnCNN_25,
    DnCNN_50.__name__: DnCNN_50,
    DnCNN_Gray.__name__: DnCNN_Gray,
    DnCNN_Gray_V2.__name__: DnCNN_Gray_V2,
    DnCNN_Color.__name__: DnCNN_Color,
    BiSeNetV1.__name__: BiSeNetV1,
    BiSeNetV2.__name__: BiSeNetV2,
    YOLOv5s_Face.__name__: YOLOv5s_Face,
    YOLOv5m_Face.__name__: YOLOv5m_Face,
    YOLOv7s_Face.__name__: YOLOv7s_Face,
    YOLOv7_Face.__name__: YOLOv7_Face,
    YOLOv7_W6_Face.__name__: YOLOv7_W6_Face,
    YOLOv7_W6_TTA_Face.__name__: YOLOv7_W6_TTA_Face,
    YOLOv5N_Face.__name__: YOLOv5N_Face,
    ArcFace_MobileFaceNet.__name__: ArcFace_MobileFaceNet,
    YoloV8X.__name__: YoloV8X,
    YoloV8M.__name__: YoloV8M,
    YoloV8N.__name__: YoloV8N,
    YoloV8S.__name__: YoloV8S,
    YOLO26n.__name__: YOLO26n,
    YOLO26s.__name__: YOLO26s,
    YOLO26m.__name__: YOLO26m,
    YOLO26l.__name__: YOLO26l,
    YOLO26x.__name__: YOLO26x,
    FastDepth.__name__: FastDepth,
    SCDepthV3.__name__: SCDepthV3,
    HarDNet68.__name__: HarDNet68,
    RegNetX_1_6GF.__name__: RegNetX_1_6GF,
    RegNetX_1_6GF_3.__name__: RegNetX_1_6GF_3,
    RegNetX_16GF.__name__: RegNetX_16GF,
    RegNetX_3_2GF.__name__: RegNetX_3_2GF,
    RegNetX_32GF.__name__: RegNetX_32GF,
    RegNetX_8GF.__name__: RegNetX_8GF,
    RegNetY_1_6GF.__name__: RegNetY_1_6GF,
    RegNetY_16GF.__name__: RegNetY_16GF,
    RegNetY_3_2GF.__name__: RegNetY_3_2GF,
    RegNetY_32GF.__name__: RegNetY_32GF,
    RegNetY_8GF.__name__: RegNetY_8GF,
    RetinaFace_MobileNet025.__name__: RetinaFace_MobileNet025,
    RetinaFace_MobileNetV1.__name__: RetinaFace_MobileNetV1,
    SCRFD10G.__name__: SCRFD10G,
    SCRFD2_5G.__name__: SCRFD2_5G,
    SCRFD500M.__name__: SCRFD500M,
    YoloV5L_Seg.__name__: YoloV5L_Seg,
    YoloV5M_Seg.__name__: YoloV5M_Seg,
    YoloV5N_Seg.__name__: YoloV5N_Seg,
    YoloV5S_Seg.__name__: YoloV5S_Seg,
    YoloV8M_Seg.__name__: YoloV8M_Seg,
    YoloV8N_Seg.__name__: YoloV8N_Seg,
    YoloV8S_Seg.__name__: YoloV8S_Seg,
    Yolo26N_Seg.__name__: Yolo26N_Seg,
    Yolo26S_Seg.__name__: Yolo26S_Seg,
    Yolo26M_Seg.__name__: Yolo26M_Seg,
    Yolo26L_Seg.__name__: Yolo26L_Seg,
    Yolo26X_Seg.__name__: Yolo26X_Seg,
    YoloXTiny.__name__: YoloXTiny,
    YoloXSWideLeaky.__name__: YoloXSWideLeaky,
    YoloXSLeaky.__name__: YoloXSLeaky,
    YoloXLLeaky.__name__: YoloXLLeaky,
    YoloV3_Gluon_416.__name__: YoloV3_Gluon_416,
    YoloV3_Gluon_608.__name__: YoloV3_Gluon_608,
    YoloV4_640.__name__: YoloV4_640,
    YoloV4_Leaky_512.__name__: YoloV4_Leaky_512,
    YoloV4Tiny_416.__name__: YoloV4Tiny_416,
    YoloV5L_640.__name__: YoloV5L_640,
    YoloV5M_640.__name__: YoloV5M_640,
    YoloV5S_640.__name__: YoloV5S_640,
    YoloV5X_640.__name__: YoloV5X_640,
    YoloV5L6_1280.__name__: YoloV5L6_1280,
    YoloV5M6_1.__name__: YoloV5M6_1,
    YoloV5M6_1280.__name__: YoloV5M6_1280,
    YoloV5M6_61_1280.__name__: YoloV5M6_61_1280,
    YoloV5N6_1280.__name__: YoloV5N6_1280,
    YoloV5N6_61_1280.__name__: YoloV5N6_61_1280,
    YoloV5S6_1280.__name__: YoloV5S6_1280,
    YoloV5S6_61_1280.__name__: YoloV5S6_61_1280,
    YoloV5X6_1280.__name__: YoloV5X6_1280,
    YoloV5M_WoSpp_640.__name__: YoloV5M_WoSpp_640,
    YoloV5S_WoSpp_640.__name__: YoloV5S_WoSpp_640,
    YoloV5S_BboxDecoding_640.__name__: YoloV5S_BboxDecoding_640,
    YoloV5S_C3tr_640.__name__: YoloV5S_C3tr_640,
    YoloV5XS_WoSpp_512.__name__: YoloV5XS_WoSpp_512,
    YoloV6L_640.__name__: YoloV6L_640,
    YoloV6M_640.__name__: YoloV6M_640,
    YoloV6S_640.__name__: YoloV6S_640,
    YoloV6N6_1280.__name__: YoloV6N6_1280,
    YoloV6S6_1280.__name__: YoloV6S6_1280,
    YoloV6N_NmsCore_640.__name__: YoloV6N_NmsCore_640,
    YoloV7D6_1280.__name__: YoloV7D6_1280,
    YoloV7E6E_1280.__name__: YoloV7E6E_1280,
    YoloXL_640.__name__: YoloXL_640,
    YoloXM_640.__name__: YoloXM_640,
    YoloXN_416.__name__: YoloXN_416,
    YoloXTiny_416.__name__: YoloXTiny_416,
    YoloXX_640.__name__: YoloXX_640,
    YOLO_DeepX_640.__name__: YOLO_DeepX_640,
    DeepLabV3MobilenetV2.__name__: DeepLabV3MobilenetV2,
    DamoYoloL.__name__: DamoYoloL,
    DamoYoloM.__name__: DamoYoloM,
    DamoYoloS.__name__: DamoYoloS,
    DamoYoloT.__name__: DamoYoloT,
    damoyolo_tinynas_l20_m.__name__: damoyolo_tinynas_l20_m,
    damoyolo_tinynas_l20_t.__name__: damoyolo_tinynas_l20_t,
    damoyolo_tinynas_l25_s.__name__: damoyolo_tinynas_l25_s,
    ViT_B_16_dfn2b.__name__: ViT_B_16_dfn2b,
    ViT_L_14_quickgelu_dfn2b.__name__: ViT_L_14_quickgelu_dfn2b,
    NanoDet.__name__: NanoDet,
    NanoDet_Plus.__name__: NanoDet_Plus,
    NanoDet_Plus_15.__name__: NanoDet_Plus_15,
    NanoDet_RepVGGA.__name__: NanoDet_RepVGGA,
    NanoDet_RepVGGA12.__name__: NanoDet_RepVGGA12,
    CenterNet_ResNet18.__name__: CenterNet_ResNet18,
    CenterNet_ResNet50.__name__: CenterNet_ResNet50,
    EfficientDet_D0.__name__: EfficientDet_D0,
    EfficientDet_D1.__name__: EfficientDet_D1,
    EfficientDet_D2.__name__: EfficientDet_D2,
    EfficientDet_D3.__name__: EfficientDet_D3,
    EfficientDet_D4.__name__: EfficientDet_D4,
    EfficientDet_D5.__name__: EfficientDet_D5,
    EfficientDet_D6.__name__: EfficientDet_D6,
    SSDVGG16.__name__: SSDVGG16,
    YOLOV8N_Pose.__name__: YOLOV8N_Pose,
    YOLOV8S_Pose.__name__: YOLOV8S_Pose,
    YOLOV8M_Pose.__name__: YOLOV8M_Pose,
    YOLOV8L_Pose.__name__: YOLOV8L_Pose,
    YOLOV8X_Pose.__name__: YOLOV8X_Pose,
    Yolo26N_Pose.__name__: Yolo26N_Pose,
    Yolo26S_Pose.__name__: Yolo26S_Pose,
    Yolo26M_Pose.__name__: Yolo26M_Pose,
    Yolo26L_Pose.__name__: Yolo26L_Pose,
    Yolo26X_Pose.__name__: Yolo26X_Pose,
    ESPCN_x2.__name__: ESPCN_x2,
    ESPCN_x3.__name__: ESPCN_x3,
    ESPCN_x4.__name__: ESPCN_x4,
    YoloV11N.__name__: YoloV11N,
    YoloV11S.__name__: YoloV11S,
    YoloV11M.__name__: YoloV11M,
    YoloV11L.__name__: YoloV11L,
    YoloV11X.__name__: YoloV11X,
    YoloV10B.__name__: YoloV10B,
    YoloV10L.__name__: YoloV10L,
    YoloV10M.__name__: YoloV10M,
    YoloV10N.__name__: YoloV10N,
    YoloV10S.__name__: YoloV10S,
    YoloV10X.__name__: YoloV10X,
    YoloV10N_PPU.__name__: YoloV10N_PPU,
    YOLOV3_608_PPU.__name__: YOLOV3_608_PPU,
    YOLOV3_416_PPU.__name__: YOLOV3_416_PPU,
    YOLOV3Tiny_PPU.__name__: YOLOV3Tiny_PPU,
    YOLOV4_PPU.__name__: YOLOV4_PPU,
    YOLOV5S_PPU.__name__: YOLOV5S_PPU,
    YOLOV7_PPU.__name__: YOLOV7_PPU,
    YOLOV7X_PPU.__name__: YOLOV7X_PPU,
    YOLOV8N_PPU.__name__: YOLOV8N_PPU,
    YOLOV8S_PPU.__name__: YOLOV8S_PPU,
    YOLOV9T_PPU.__name__: YOLOV9T_PPU,
    YOLOXS_PPU.__name__: YOLOXS_PPU,
    YOLOV11N_PPU.__name__: YOLOV11N_PPU,
    YOLOV12N_PPU.__name__: YOLOV12N_PPU,
    InceptionV1.__name__: InceptionV1,
    InceptionV3.__name__: InceptionV3,
    MnasNet0_5.__name__: MnasNet0_5,
    MnasNet0_75.__name__: MnasNet0_75,
    MnasNet1_0.__name__: MnasNet1_0,
    MnasNet1_3.__name__: MnasNet1_3,
    RepVGGA2.__name__: RepVGGA2,
    BeitBasePatch16_224.__name__: BeitBasePatch16_224,
    BeitLargePatch16_224.__name__: BeitLargePatch16_224,
    BeitBasePatch16_384.__name__: BeitBasePatch16_384,
    BeitLargePatch16_384.__name__: BeitLargePatch16_384,
    DeiTBase_224.__name__: DeiTBase_224,
    DeiTBase_384.__name__: DeiTBase_384,
    DeiTBaseDistilled_224.__name__: DeiTBaseDistilled_224,
    DeiTBaseDistilled_384.__name__: DeiTBaseDistilled_384,
    DeiTSmall_224.__name__: DeiTSmall_224,
    DeiTSmallDistilled_224.__name__: DeiTSmallDistilled_224,
    DeiTTiny_224.__name__: DeiTTiny_224,
    DeiTTinyDistilled_224.__name__: DeiTTinyDistilled_224,
    ViT_B_32_256_datacomp_s34b_b68k.__name__: ViT_B_32_256_datacomp_s34b_b68k,
    ViT_B_16_quickgelu_metaclip_fullcc.__name__: ViT_B_16_quickgelu_metaclip_fullcc,
    ViT_L_14_CLIPA_datacomp1b.__name__: ViT_L_14_CLIPA_datacomp1b,
    ViT_L_14_datacomp_xl_s13b_b90k.__name__: ViT_L_14_datacomp_xl_s13b_b90k,
    ViT_L_14_336_openai.__name__: ViT_L_14_336_openai,
    ViT_L_14_CLIPA_336_datacomp1b.__name__: ViT_L_14_CLIPA_336_datacomp1b,
    RN50x64_openai.__name__: RN50x64_openai,
    RN50x16_openai.__name__: RN50x16_openai,
    ConvNextBase_w_laion2b_s13b_b82k_augreg.__name__: ConvNextBase_w_laion2b_s13b_b82k_augreg,
    ConvNextBase_w_320_laion_aesthetic_s13b_b82k.__name__: ConvNextBase_w_320_laion_aesthetic_s13b_b82k,
    ConvNextLarge_d_laion2b_s26b_b102k_augreg.__name__: ConvNextLarge_d_laion2b_s26b_b102k_augreg,
    ConvNextLarge_w_320_laion2b_s29b_b131k_ft_soup.__name__: ConvNextLarge_w_320_laion2b_s29b_b131k_ft_soup,
    ULFGFD_RFB_320.__name__: ULFGFD_RFB_320,
    ULFGFD_RFB_320_WO_PP.__name__: ULFGFD_RFB_320_WO_PP,
    ULFGFD_RFB_640.__name__: ULFGFD_RFB_640,
    ULFGFD_Slim_320.__name__: ULFGFD_Slim_320,
    ULFGFD_Slim_320_WO_PP.__name__: ULFGFD_Slim_320_WO_PP,
    ArcFace_IResNet100_MS1M.__name__: ArcFace_IResNet100_MS1M,
    ArcFace_IResNet50_MS1M.__name__: ArcFace_IResNet50_MS1M,
    ArcFace_R50.__name__: ArcFace_R50,
    CenterPose_RegNetX_1_6GF_FPN.__name__: CenterPose_RegNetX_1_6GF_FPN,
    CenterPose_RegNetX_800MF.__name__: CenterPose_RegNetX_800MF,
    CenterPose_RepVGG_A0.__name__: CenterPose_RepVGG_A0,
    SegFormer_b0_512x1024.__name__: SegFormer_b0_512x1024,
    SegFormer_b0_512x1024_H.__name__: SegFormer_b0_512x1024_H,
    FastSAM_S.__name__: FastSAM_S,
    MediaPipeHandsLite.__name__: MediaPipeHandsLite,
    FaceAttrResnetV1_18.__name__: FaceAttrResnetV1_18,
    DeepMAR_ResNet18.__name__: DeepMAR_ResNet18,
    DeepMAR_ResNet50.__name__: DeepMAR_ResNet50,
    OSNetX1_0_ReID.__name__: OSNetX1_0_ReID,
    RepVGGA0_ReID.__name__: RepVGGA0_ReID,
    UNet_MobileNetV2.__name__: UNet_MobileNetV2,
    TDDFA_V2_MobileNet05.__name__: TDDFA_V2_MobileNet05,
    TDDFA_V2_MobileNetV1.__name__: TDDFA_V2_MobileNetV1,
    TDDFA_V2_ResNet22.__name__: TDDFA_V2_ResNet22,
    ZeroDCE.__name__: ZeroDCE,
}
